<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <PackageId>DotNetBoost.Settings.FluentValidation</PackageId>
    <Description>FluentValidation integration for DotNetBoost.Settings.</Description>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../DotNetBoost.Settings.Core/DotNetBoost.Settings.Core.csproj" />
    <PackageReference Include="FluentValidation" />
  </ItemGroup>
</Project>
