<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <PackageId>DotNetBoost.Settings.MongoDb</PackageId>
    <Description>MongoDB provider for DotNetBoost.Settings.</Description>
  </PropertyGroup>
  <ItemGroup>
    <InternalsVisibleTo Include="DotNetBoost.Settings.IntegrationTests" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="../DotNetBoost.Settings.Core/DotNetBoost.Settings.Core.csproj" />
    <PackageReference Include="MongoDB.Driver" />
    <PackageReference Include="Microsoft.Extensions.Hosting.Abstractions" />
  </ItemGroup>
</Project>
