using System.Net;
using System.Net.Http.Json;
using System.Text.Json;
using DotNetBoost.Settings.Core.Attributes;
using DotNetBoost.Settings.Core.Interfaces;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Routing;
using Microsoft.Extensions.DependencyInjection;

namespace DotNetBoost.Settings.ApiTests;

/// <summary>
/// Nothing used to enumerate the <c>[SettingGroup]</c> classes or describe a group's
/// properties, so a "form generated from the class" was really generated by guessing at the
/// shape of a JSON response — and the bounds it enforced lived in the client, unenforced on
/// the server and reinvented by every new client.
/// <para>
/// Neither endpoint returns a stored value; several of these tests exist to keep it that way.
/// </para>
/// </summary>
public class DiscoveryEndpointTests
{
    [Fact]
    public async Task GroupList_ContainsEveryRegisteredGroup()
    {
        await using var app = await TestApp.StartAsync();

        var groups = await app.Client.GetFromJsonAsync<List<JsonElement>>("/api/settings");

        var routes = groups!.Select(g => g.GetProperty("route").GetString()).ToList();
        Assert.Contains("api-test", routes);
        Assert.Contains("api-projected", routes);
        Assert.Contains("api-secured", routes);
    }

    [Fact]
    public async Task GroupList_ReportsThePersistenceKey_NotTheClassName()
    {
        await using var app = await TestApp.StartAsync();

        var groups = await app.Client.GetFromJsonAsync<List<JsonElement>>("/api/settings");

        var apiTest = groups!.Single(g => g.GetProperty("route").GetString() == "api-test");
        Assert.Equal("api-test-group", apiTest.GetProperty("name").GetString());
        Assert.NotEqual(nameof(ApiTestSettings), apiTest.GetProperty("name").GetString());
    }

    [Fact]
    public async Task GroupList_SaysWhichGroupsRequireAuthorization()
    {
        await using var app = await TestApp.StartAsync();

        var groups = await app.Client.GetFromJsonAsync<List<JsonElement>>("/api/settings");

        Assert.True(Find(groups!, "api-secured").GetProperty("requiresAuthorization").GetBoolean());
        Assert.False(Find(groups!, "api-test").GetProperty("requiresAuthorization").GetBoolean());
    }

    [Fact]
    public async Task GroupList_ReturnsNoValues()
    {
        await using var app = await TestApp.StartAsync();

        // The stub store seeds api-test-group's Host. It must not appear anywhere in a listing.
        var body = await app.Client.GetStringAsync("/api/settings");

        Assert.DoesNotContain("stored.example.com", body, StringComparison.Ordinal);
        Assert.DoesNotContain("host", body, StringComparison.OrdinalIgnoreCase);
    }

    [Fact]
    public async Task GroupList_CanBeTurnedOff()
    {
        await using var app = await TestApp.StartAsync(includeDiscovery: false);

        var response = await app.Client.GetAsync("/api/settings");

        Assert.Equal(HttpStatusCode.NotFound, response.StatusCode);
    }

    [Fact]
    public async Task Schema_NamesPropertiesTheWayTheGetBodyDoes()
    {
        await using var app = await TestApp.StartAsync();

        var schema = await app.Client.GetFromJsonAsync<JsonElement>("/api/settings/api-described/schema");
        var body   = await app.Client.GetFromJsonAsync<JsonElement>("/api/settings/api-described");

        var schemaNames = schema.GetProperty("properties")
            .EnumerateArray()
            .Select(p => p.GetProperty("name").GetString()!)
            .OrderBy(n => n, StringComparer.Ordinal)
            .ToList();

        var bodyNames = body.EnumerateObject()
            .Select(p => p.Name)
            .OrderBy(n => n, StringComparer.Ordinal)
            .ToList();

        Assert.Equal(bodyNames, schemaNames);
    }

    [Fact]
    public async Task Schema_ReportsTypes()
    {
        await using var app = await TestApp.StartAsync();

        var properties = await PropertiesOf(app, "api-described");

        Assert.Equal("String",  properties["host"].GetProperty("type").GetString());
        Assert.Equal("Int32",   properties["port"].GetProperty("type").GetString());
        Assert.Equal("Boolean", properties["useSsl"].GetProperty("type").GetString());
    }

    [Fact]
    public async Task Schema_ReportsTheSettingDefault_WhenThereIsOne()
    {
        await using var app = await TestApp.StartAsync();

        var properties = await PropertiesOf(app, "api-described");

        Assert.Equal(2525, properties["port"].GetProperty("default").GetInt32());
    }

    [Fact]
    public async Task Schema_FallsBackToTheClassInitialiser_WithoutASettingDefault()
    {
        await using var app = await TestApp.StartAsync();

        var properties = await PropertiesOf(app, "api-described");

        Assert.Equal("smtp.example.com", properties["host"].GetProperty("default").GetString());
        Assert.True(properties["useSsl"].GetProperty("default").GetBoolean());
    }

    /// <summary>
    /// A compile-time default on a secret property is a value like any other, and this
    /// endpoint is meant to be safe to expose more widely than values are.
    /// </summary>
    [Fact]
    public async Task Schema_MarksSensitiveProperties_AndWithholdsTheirDefault()
    {
        await using var app = await TestApp.StartAsync();

        var properties = await PropertiesOf(app, "api-described");

        Assert.True(properties["password"].GetProperty("sensitive").GetBoolean());
        Assert.Equal(JsonValueKind.Null, properties["password"].GetProperty("default").ValueKind);
        Assert.False(properties["host"].GetProperty("sensitive").GetBoolean());
    }

    [Fact]
    public async Task Schema_ReturnsNoStoredValues()
    {
        await using var app = await TestApp.StartAsync();

        // api-test-group has a stored Host of "stored.example.com".
        var body = await app.Client.GetStringAsync("/api/settings/api-test/schema");

        Assert.DoesNotContain("stored.example.com", body, StringComparison.Ordinal);
    }

    /// <summary>
    /// Asserted on the endpoint metadata rather than on a status code: the test host has no
    /// authentication middleware, so an authorized request throws instead of answering 401.
    /// The metadata is the thing that matters anyway — a group's endpoints must not disagree
    /// about who may look at it.
    /// </summary>
    [Fact]
    public async Task Schema_CarriesTheSameAuthorization_AsTheGroupsOtherEndpoints()
    {
        await using var app = await TestApp.StartAsync();

        Assert.True(IsAuthorized(app, "api/settings/api-secured/"));
        Assert.True(IsAuthorized(app, "api/settings/api-secured/schema"));

        // And an anonymous group's schema stays anonymous.
        Assert.False(IsAuthorized(app, "api/settings/api-described/schema"));
    }

    /// <summary>
    /// Whether every endpoint on <paramref name="routePattern"/> is authorized. A pattern can
    /// carry more than one method — GET and POST share the group's root — and they must agree.
    /// </summary>
    private static bool IsAuthorized(TestApp app, string routePattern)
    {
        var endpoints = app.Services.GetRequiredService<EndpointDataSource>()
            .Endpoints
            .OfType<RouteEndpoint>()
            .Where(e => e.RoutePattern.RawText == routePattern)
            .ToList();

        Assert.NotEmpty(endpoints);
        return endpoints.TrueForAll(e => e.Metadata.GetMetadata<IAuthorizeData>() is not null);
    }

    [Fact]
    public async Task Schema_CanBeTurnedOff()
    {
        await using var app = await TestApp.StartAsync(includeDiscovery: false);

        var response = await app.Client.GetAsync("/api/settings/api-described/schema");

        Assert.Equal(HttpStatusCode.NotFound, response.StatusCode);
    }

    [Fact]
    public async Task Schema_WithNoContributor_IsValidAndCarriesNoConstraints()
    {
        await using var app = await TestApp.StartAsync();

        var properties = await PropertiesOf(app, "api-described");

        Assert.Equal(JsonValueKind.Null, properties["port"].GetProperty("constraints").ValueKind);
    }

    [Fact]
    public async Task Schema_WithAContributor_PublishesItsConstraints()
    {
        await using var app = await TestApp.StartAsync(
            s => s.AddSingleton<ISettingSchemaContributor, StubSchemaContributor>());

        var properties = await PropertiesOf(app, "api-described");

        var port = properties["port"].GetProperty("constraints");
        Assert.Equal(1,      port.GetProperty("min").GetInt32());
        Assert.Equal(65_535, port.GetProperty("max").GetInt32());

        // A property the contributor said nothing about still reports none.
        Assert.Equal(JsonValueKind.Null, properties["useSsl"].GetProperty("constraints").ValueKind);
    }

    /// <summary>
    /// A schema is a convenience. A contributor that cannot describe itself should cost the
    /// constraints, not the endpoint.
    /// </summary>
    [Fact]
    public async Task Schema_SurvivesAContributorThatThrows()
    {
        await using var app = await TestApp.StartAsync(
            s => s.AddSingleton<ISettingSchemaContributor, ThrowingSchemaContributor>());

        var response = await app.Client.GetAsync("/api/settings/api-described/schema");

        Assert.Equal(HttpStatusCode.OK, response.StatusCode);
        var properties = await PropertiesOf(app, "api-described");
        Assert.Equal(JsonValueKind.Null, properties["port"].GetProperty("constraints").ValueKind);
    }

    /// <summary>
    /// The case this merge exists for. A consumer publishing something this library cannot
    /// know about — a rule carried by an attribute from another package — must not silently
    /// delete the validation rules by registering alongside them.
    /// </summary>
    [Fact]
    public async Task Schema_MergesContributorsDescribingDifferentProperties()
    {
        await using var app = await TestApp.StartAsync(s =>
        {
            s.AddSingleton<ISettingSchemaContributor, StubSchemaContributor>();
            s.AddSingleton<ISettingSchemaContributor>(_ => new TranslatedContributor(nameof(DescribedSettings.Host)));
        });

        var properties = await PropertiesOf(app, "api-described");

        Assert.Equal(1, properties["port"].GetProperty("constraints").GetProperty("min").GetInt32());
        Assert.True(properties["host"].GetProperty("constraints").GetProperty("translated").GetBoolean());
    }

    [Fact]
    public async Task Schema_MergesContributorsDescribingTheSameProperty()
    {
        await using var app = await TestApp.StartAsync(s =>
        {
            s.AddSingleton<ISettingSchemaContributor, StubSchemaContributor>();
            s.AddSingleton<ISettingSchemaContributor>(_ => new TranslatedContributor(nameof(DescribedSettings.Port)));
        });

        var port = (await PropertiesOf(app, "api-described"))["port"].GetProperty("constraints");

        // Both contributors' constraints survive on the one property.
        Assert.Equal(1,      port.GetProperty("min").GetInt32());
        Assert.Equal(65_535, port.GetProperty("max").GetInt32());
        Assert.True(port.GetProperty("translated").GetBoolean());
    }

    /// <summary>
    /// Last-wins would make the published schema depend on registration order, which is the
    /// defect being fixed — so the value is asserted, not merely that one of them landed.
    /// </summary>
    [Fact]
    public async Task Schema_OnACollidingConstraint_KeepsTheFirstRegistered()
    {
        await using var app = await TestApp.StartAsync(s =>
        {
            s.AddSingleton<ISettingSchemaContributor, StubSchemaContributor>();   // min = 1
            s.AddSingleton<ISettingSchemaContributor>(_ => new MinOverridingContributor(99));
        });

        var port = (await PropertiesOf(app, "api-described"))["port"].GetProperty("constraints");

        Assert.Equal(1, port.GetProperty("min").GetInt32());

        // The loser's other constraints still land — only the colliding key is dropped.
        Assert.Equal(7, port.GetProperty("maxLength").GetInt32());
    }

    /// <summary>
    /// The case that justifies wrapping each contributor rather than the loop: it is what
    /// silently regresses if someone later hoists the try/catch outward.
    /// </summary>
    [Fact]
    public async Task Schema_AContributorThatThrows_DoesNotCostTheOthersTheirConstraints()
    {
        await using var app = await TestApp.StartAsync(s =>
        {
            s.AddSingleton<ISettingSchemaContributor, ThrowingSchemaContributor>();
            s.AddSingleton<ISettingSchemaContributor, StubSchemaContributor>();
        });

        var response = await app.Client.GetAsync("/api/settings/api-described/schema");
        Assert.Equal(HttpStatusCode.OK, response.StatusCode);

        var port = (await PropertiesOf(app, "api-described"))["port"].GetProperty("constraints");
        Assert.Equal(1,      port.GetProperty("min").GetInt32());
        Assert.Equal(65_535, port.GetProperty("max").GetInt32());
    }

    [Fact]
    public async Task Schema_DoesNotConsultAContributorThatCannotDescribeTheType()
    {
        var unrelated = new RecordingContributor(canDescribe: false);
        var applies   = new RecordingContributor(canDescribe: true);

        await using var app = await TestApp.StartAsync(s =>
        {
            s.AddSingleton<ISettingSchemaContributor>(_ => unrelated);
            s.AddSingleton<ISettingSchemaContributor>(_ => applies);
        });

        await app.Client.GetAsync("/api/settings/api-described/schema");

        Assert.Equal(0, unrelated.DescribeCalls);
        Assert.True(applies.DescribeCalls > 0);
    }

    private static JsonElement Find(List<JsonElement> groups, string route)
        => groups.Single(g => g.GetProperty("route").GetString() == route);

    private static async Task<Dictionary<string, JsonElement>> PropertiesOf(TestApp app, string route)
    {
        var schema = await app.Client.GetFromJsonAsync<JsonElement>($"/api/settings/{route}/schema");
        return schema.GetProperty("properties")
            .EnumerateArray()
            .ToDictionary(p => p.GetProperty("name").GetString()!, p => p);
    }

    private sealed class StubSchemaContributor : ISettingSchemaContributor
    {
        public bool CanDescribe(Type type) => type == typeof(DescribedSettings);

        public IReadOnlyDictionary<string, IReadOnlyDictionary<string, object?>> Describe(Type type)
            => new Dictionary<string, IReadOnlyDictionary<string, object?>>
            {
                [nameof(DescribedSettings.Port)] = new Dictionary<string, object?>
                {
                    ["min"] = 1,
                    ["max"] = 65_535
                }
            };
    }

    /// <summary>
    /// Stands in for a contributor from another package: it publishes a constraint
    /// DotNetBoost.Settings has never heard of, which is what this port exists for.
    /// </summary>
    private sealed class TranslatedContributor(string propertyName) : ISettingSchemaContributor
    {
        public bool CanDescribe(Type type) => type == typeof(DescribedSettings);

        public IReadOnlyDictionary<string, IReadOnlyDictionary<string, object?>> Describe(Type type)
            => new Dictionary<string, IReadOnlyDictionary<string, object?>>
            {
                [propertyName] = new Dictionary<string, object?> { ["translated"] = true }
            };
    }

    /// <summary>Collides with <see cref="StubSchemaContributor"/> on <c>min</c>, and only on that.</summary>
    private sealed class MinOverridingContributor(int min) : ISettingSchemaContributor
    {
        public bool CanDescribe(Type type) => type == typeof(DescribedSettings);

        public IReadOnlyDictionary<string, IReadOnlyDictionary<string, object?>> Describe(Type type)
            => new Dictionary<string, IReadOnlyDictionary<string, object?>>
            {
                [nameof(DescribedSettings.Port)] = new Dictionary<string, object?>
                {
                    ["min"]       = min,
                    ["maxLength"] = 7
                }
            };
    }

    private sealed class RecordingContributor(bool canDescribe) : ISettingSchemaContributor
    {
        public int DescribeCalls { get; private set; }

        public bool CanDescribe(Type type) => canDescribe;

        public IReadOnlyDictionary<string, IReadOnlyDictionary<string, object?>> Describe(Type type)
        {
            DescribeCalls++;
            return new Dictionary<string, IReadOnlyDictionary<string, object?>>();
        }
    }

    private sealed class ThrowingSchemaContributor : ISettingSchemaContributor
    {
        public bool CanDescribe(Type type) => true;

        public IReadOnlyDictionary<string, IReadOnlyDictionary<string, object?>> Describe(Type type)
            => throw new InvalidOperationException("cannot read the rules");
    }
}

/// <summary>A group with one of each thing the schema has to report.</summary>
[SettingGroup("api-described")]
public class DescribedSettings
{
    public string Host { get; set; } = "smtp.example.com";

    [SettingDefault(2525)]
    public int Port { get; set; } = 587;

    public bool UseSsl { get; set; } = true;

    [Sensitive]
    public string Password { get; set; } = "compile-time-default";
}

[SettingGroup("api-secured")]
[Authorize]
public class SecuredSettings
{
    public string Host { get; set; } = string.Empty;
}
